### ISSUE TITLE
bug: hitting space bar while typing into search bar activates keyboard shortcut to play/pause instead

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#104]
When typing into the search bar, when a user adds a space for, say, multiple search terms, that activates the keyboard shortcut to pause the sound if it's playing or play the sound if it isn't. In addition, the space will not show up in the search bar.

I think looking at some of the changes in #66 and #85 might be helpful.

**Comment by hamirmahal** [comment]
I think looking at [a relevant issue in the repository we used for this functionality](https://github.com/jamiebuilds/tinykeys/issues/17) might be helpful.

**Comment by amilajack** [comment]
Good catch. Maybe we can check if the input search is focused. If it isnt focused then we know the user isn't typing into it so we allow the spacebar and all other shortcuts to proceed.

**Comment by amilajack** [comment]
@hamirmahal Interested in taking this on?

**Comment by hamirmahal** [comment]
> @hamirmahal Interested in taking this on?

Sure! But, maybe not immediately. I definitely want to completely finish the pull request I have open, first, before opening new ones.
