### ISSUE TITLE
bug: typing into search bar while on an arbitrary sounds page doesn't automatically show search results

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#107]
When users type into the search bar on an [arbitrary sound page](https://freesound-player.netlify.app/sound/462806), search results don't automatically appear.

Currently, users would have to click the `Home` button to see the results of their search.

One alternative is that search results automatically appear on the page as the user types into the search bar.

**Comment by amilajack** [comment]
+1. I really love this idea! I really love tailwind's search implementation:
https://tailwindcss.com/
If you haven't already, I recommend searching some stuff on it to get a feel for what the experience is like. I'll work on a design for this shortly 😄

**Comment by amilajack** [comment]
Fixed in https://github.com/amilajack/freesound-player/pull/167
