### ISSUE TITLE
ui redesign: update description's design

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#111]
The description on dark mode no longer uses a primary color background.

## 🙅‍♀️ Bad (current implementation)

**Light Mode**
<img width="1680" alt="Screen Shot 2020-10-21 at 9 07 34 AM" src="https://user-images.githubusercontent.com/6374832/96747211-dc6dfc00-137c-11eb-8d8f-cb1553252e97.png">

**Dark Mode**
<img width="1680" alt="Screen Shot 2020-10-21 at 9 08 01 AM" src="https://user-images.githubusercontent.com/6374832/96747278-ed1e7200-137c-11eb-99ab-99b086909ba3.png">

## 👍 Good (new design)

**Light Mode**
<img width="805" alt="Screen Shot 2020-10-21 at 9 06 50 AM" src="https://user-images.githubusercontent.com/6374832/96747128-c3fde180-137c-11eb-97a2-615b9b598bd8.png">
**Dark Mode**
<img width="1265" alt="Screen Shot 2020-10-21 at 9 03 33 AM" src="https://user-images.githubusercontent.com/6374832/96746691-4cc84d80-137c-11eb-9e0d-f8be27820434.png">

**Comment by amilajack** [comment]
reopened this because the sound description implementation has too much padding compared to the design

**Comment by akshara-sun** [comment]
@amilajack I'm not sure if I see it, could you please provide screenshots for comparison? Thanks

**Comment by amilajack** [comment]
<img width="890" alt="Screen Shot 2020-11-06 at 1 16 06 PM" src="https://user-images.githubusercontent.com/6374832/98415486-3b489c00-2032-11eb-9208-3b42287b2dec.png">
![Uploading Screen Shot 2020-11-06 at 1.16.16 PM.png…]()
