### ISSUE TITLE
Use IonIcons component to integrate ion icons

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#118]
Currently we're importing a URL to ionicons in our `index.html` file. This means that we're loading the entire ionicons library. This means that we're loading a ton of icons that we don't need. The Ion framework provides a react component to let you integrate components:

### Install
```
yarn add @ionic/react ionicons
```

### Usage
```tsx
import { camera } from 'ionicons/icons';
import { IonIcon } from '@ionic/react';

<IonIcon icon={camera} />
```

**Comment by hamirmahal** [comment]
> Currently we're importing a URL to ionicons in our `index.html` file. This means that we're loading the entire ionicons library. This means that we're loading a ton of icons that we don't need.

For reference, I believe the pertinent programming is [lines 92 and 93 of `/public/index.html`](https://github.com/amilajack/freesound-player/blob/370ed4a983e32c7fcbd0a60f3468a0cb67025b6f/public/index.html#L92).

**Comment by amilajack** [comment]
correct 💯

**Comment by hamirmahal** [comment]
> ### Usage
> ```tsx
> import { camera } from 'ionicons/icons';
> import { IonIcon } from '@ionic/react';
> 
> <IonIcon icon={camera} />
> ```

I believe the only places we need to make modifications related to this issue after removing the aforementioned lines from `index.html` is [`/src/Sound.js`](https://github.com/amilajack/freesound-player/blob/57f20bc9891b832bf62f3dc83b743ed368093368/src/Sound.js) on [line 112](https://github.com/amilajack/freesound-player/blob/57f20bc9891b832bf62f3dc83b743ed368093368/src/Sound.js#L112), [line 127](https://github.com/amilajack/freesound-player/blob/57f20bc9891b832bf62f3dc83b743ed368093368/src/Sound.js#L127), [line 128](https://github.com/amilajack/freesound-player/blob/57f20bc9891b832bf62f3dc83b743ed368093368/src/Sound.js#L128), [line 131](https://github.com/amilajack/freesound-player/blob/57f20bc9891b832bf62f3dc83b743ed368093368/src/Sound.js#L131), and [line 133](https://github.com/amilajack/freesound-player/blob/57f20bc9891b832bf62f3dc83b743ed368093368/src/Sound.js#L133), and in [`/src/App.js`](https://github.com/amilajack/freesound-player/blob/6ca5470bdb15a5a95f13b410755e949d5cd3793c/src/App.js) on [line 62](https://github.com/amilajack/freesound-player/blob/6ca5470bdb15a5a95f13b410755e949d5cd3793c/src/App.js#L62) and [line 81](https://github.com/amilajack/freesound-player/blob/6ca5470bdb15a5a95f13b410755e949d5cd3793c/src/App.js#L81).

Hopefully, that helps whoever ends up taking this issue.

> correct 💯

Thanks for the feedback!
