### ISSUE TITLE
infra: lack of specification of React version causing eslint check to fail on git commit attempt

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#119]
I think the React version not being specified in our eslint settings is causing an error message to occur each time I try to make a commit.

![Screen Shot 2020-10-23 at 4 46 21 PM](https://user-images.githubusercontent.com/43425812/97062320-4938f000-154f-11eb-91d7-fb56f8af6d69.png)

This is easy to circumvent, by entering the command `git commit --no-verify` as the error message suggests, but I'm wondering if it would be cleaner to just make the appropriate changes to our eslint settings.

**Comment by amilajack** [comment]
The error is comming from the react/no-unesaped-entities rule, which is unrelated to the react version. It means that we're not escaping certain characters. its not very high priority tho. We can [ignore the rule for that line](https://eslint.org/docs/2.13.1/user-guide/configuring#disabling-rules-with-inline-comments) with a `eslint-disable-next-line` comment above that line

**Comment by hamirmahal** [comment]
Okay, got it. I added that rule and the warning didn't show up when I did `git commit`. Thank you!
