### ISSUE TITLE
add react-helmet integration to update title tags for different pages

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#126]
When the user navigates to a sound, the page's title should update to something like `FreeSound Player - Mustang Engine`. Right now it just says `FreeSound Player`. React helmet makes that easy to do in react. It provides a declarative API for the imperative `document.title` DOM API

https://github.com/nfl/react-helmet

**Comment by hamirmahal** [comment]
Whoa! I didn't know the NFL had GitHub repositories.
