### ISSUE TITLE
animate modal opening and closing

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#127]
See https://campfire.gg/ for a great example of an opening modal animation. Click the login button to open the modal. There are a few paths we could take to do this. We could either use css to animate the modal or we could use [react-spring](https://www.react-spring.io/docs/hooks/basics), which provides higher level animation primitives. For now we should take the plain css approach (not using tailwind is fine in this case).

See https://github.com/reactjs/react-modal/issues/125 for examples of animation with react-modal. Copy and paste the css in the examples to try to get the modal to animate. Once you get the animation to work, try to make it match the animation of campfire's modal

**Comment by hamirmahal** [comment]
> See [reactjs/react-modal#125](https://github.com/reactjs/react-modal/issues/125) for examples of animation with react-modal. Copy and paste the css in the examples to try to get the modal to animate. Once you get the animation to work, try to make it match the animation of campfire's modal

I think the [transitions page of the react-modal documentation](http://reactcommunity.org/react-modal/styles/transitions/) might also be helpful, so I'm leaving the link in case someone visiting this page in the future wants to visit that page easily.
