### ISSUE TITLE
show download modal if user clicks on download button when not logged in

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#133]
When a user is not logged in and they click the download button, they should get the following modal:

<img width="712" alt="Screen Shot 2020-11-07 at 11 54 42 AM" src="https://user-images.githubusercontent.com/6374832/98450239-069b1a00-20f0-11eb-97a5-15db26f8c770.png">

The following changes need to be made to get this working:
- Create the download modal react component
- Show the download button even if user is not logged in

```
// pseudo code

onDownloadButtonClick=() => {
  if (userLoggedIn) {
   downloadSound();
  } else {
    showDownloadLoginModal();
  }
}
```

**Comment by hamirmahal** [comment]
Do we actually have a download button for this modal to appear after clicking?

**Comment by amilajack** [comment]
Yea @akshara-sun is working on this in #128
