### ISSUE TITLE
feat: add github corner

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#14]
This would just be a nice feature, especially as someone who's working on the repository.

It makes it really easy when I run <code>npm start</code>, and all I have to do to open the repository on GitHub is scroll to the bottom of the <code>localhost:3000/freesound-player</code> page that just opened.

It might also make it easier for potential contributors to find out where they want to add changes to the source code.

We can see an example of this in my Todolist application, of which there is a screenshot below.

![Link to repository's source code accessible from web application 2020-08-11 141034](https://user-images.githubusercontent.com/43425812/89949329-96f2bd00-dbdc-11ea-8142-3296da859e82.jpg)

**Comment by amilajack** [comment]
This is also a popular way of doing this:
https://github.com/tholman/github-corners

**Comment by hamirmahal** [comment]
Whoa! That's really slick. Thanks for letting me know about this.

**Comment by amilajack** [comment]
Glad you like the idea! We should update the title to "feat: add github corner" (feat short for feature)

**Comment by hamirmahal** [comment]
Added! It's subtle.

![GitHub corner added to freesound-player](https://user-images.githubusercontent.com/43425812/89973929-819a8480-dc16-11ea-93b7-bbb78795061f.png)

It's in the top-righthand corner.

![GitHub corner in top-righthand corner](https://user-images.githubusercontent.com/43425812/89974001-b3abe680-dc16-11ea-82a2-3dd2843aba11.png)
