### ISSUE TITLE
update <title> in index.html

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#15]
I want to change the title of the application from the default name of "React App".

![current title of application is 'React App' 2020-08-11 143750](https://user-images.githubusercontent.com/43425812/89951474-57c66b00-dbe0-11ea-93f3-b261482023ec.jpg)

**Comment by hamirmahal** [comment]
Done.

![title updated to 'Freesound Web Client' 2020-08-11 143750](https://user-images.githubusercontent.com/43425812/89952265-c35d0800-dbe1-11ea-9208-a517f08102e2.jpg)

**Comment by amilajack** [comment]
How about just `Freesound`

**Comment by hamirmahal** [comment]
That works

**Comment by hamirmahal** [comment]
Done!

![title changed from "Freesound Web Client" to "Freesound"](https://user-images.githubusercontent.com/43425812/89969392-1e572500-dc0b-11ea-864e-a50a77a3e12d.png)
