### ISSUE TITLE
safely render html descriptions

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#150]
Sometimes descriptions contain simple HTML such as links (see example below). We can actually the description string as an html element. Typically this can be a security vulnerability if handled incorrectly.

**Read https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml for more on this**. Also read https://medium.com/better-programming/what-is-dangerouslysetinnerhtml-6d6a98cbc187 to see how to implement this

<img width="1457" alt="Screen Shot 2020-11-08 at 1 48 47 PM" src="https://user-images.githubusercontent.com/6374832/98485156-24887d80-21c9-11eb-8622-ed1ecce6b0c9.png">

**Comment by hamirmahal** [comment]
/sound/464889 is an example sound that would have noticeable changes in its description field.
