### ISSUE TITLE
larger github svg logo

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#17]
I think we should increase the size of the logo to make it more visible:

<img width="164" alt="Screen Shot 2020-08-12 at 12 18 34 PM" src="https://user-images.githubusercontent.com/6374832/90058006-08db0d00-dc96-11ea-9f16-6464063814dd.png">

**Comment by hamirmahal** [comment]
How's this?

I updated <code>height, width</code> from <code>4vmin</code> to <code>5vmin</code>. You can see it immediately below.

![GitHub Corner's height and width updated to 5vmin](https://user-images.githubusercontent.com/43425812/90086348-152f8c00-dccf-11ea-801d-1a7ca7a65aa4.png)

`6vmin` immediately below.

![GitHub Corner's height and width updated to 6vmin](https://user-images.githubusercontent.com/43425812/90086420-3d1eef80-dccf-11ea-85d1-8426e704b783.png)

<code>7vmin</code> below.

![GitHub Corner's height and width updated to 7vmin](https://user-images.githubusercontent.com/43425812/90086491-5f187200-dccf-11ea-8cd1-7dea98ac991b.png)

<code>8vmin</code> below.

![GitHub Corner's height and width updated to 8vmin](https://user-images.githubusercontent.com/43425812/90086552-8b33f300-dccf-11ea-9099-4f044cfa853b.png)

<code>9vmin</code> below.

![GitHub Corner's height and width updated to 9vmin](https://user-images.githubusercontent.com/43425812/90086663-cb937100-dccf-11ea-9344-13ca13a478bc.png)

<code>10vmin</code> below. Which should we do?

![GitHub Corner's height and width updated to 10vmin](https://user-images.githubusercontent.com/43425812/90086711-e9f96c80-dccf-11ea-819d-63895bcce1bc.png)

**Comment by amilajack** [comment]
Much better 🥳

**Comment by hamirmahal** [comment]
Fixed!

Original appearance with `height, width` set to `4vmin` immediately below.

![Freesound player homepage original appearance with GitHub Corner `height, width` set to `4vmin`](https://user-images.githubusercontent.com/43425812/90172509-f7f2d000-dd57-11ea-9dea-4f81a99b80c9.png)

This is what the appearance of the GitHub Corner now looks like on the live webpage at `https://amilajack.github.io/freesound-player/` after updating `height` and `width` to `10vmin`.

![Freesound player homepage appearance with GitHub Corner `height, width` set to `10vmin`](https://user-images.githubusercontent.com/43425812/90207606-8dfc1a00-dd9b-11ea-99aa-ed830f0685a8.png)
