### ISSUE TITLE
infra: src/components/Search.js might be a possible duplicate of src/components/Input.js

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#177]
I think [`src/components/Search.js`](https://github.com/amilajack/freesound-player/blob/master/src/components/Search.js) might be a duplicate of [`src/components/Input.js`](https://github.com/amilajack/freesound-player/blob/master/src/components/Input.js).

We use [`src/components/Input.js`](https://github.com/amilajack/freesound-player/blob/master/src/components/Input.js) in [line 4 of `Nav.js`](https://github.com/amilajack/freesound-player/blob/8d7ee71f33581672ebd69933c5e74c72222ef964/src/Nav.js#L4), so I'm reasonably certain that [`src/components/Input.js`](https://github.com/amilajack/freesound-player/blob/master/src/components/Input.js) should stay.

At the very least, [the name of the functional component on line 3 of `Search.js`](https://github.com/amilajack/freesound-player/blob/8d7ee71f33581672ebd69933c5e74c72222ef964/src/components/Search.js#L3), `Input`, doesn't match the name of the file, `Search.js`, so that might be something we need to change even if `Search.js` isn't a duplicate of `Input.js`.

**Comment by amilajack** [comment]
Fixed
