### ISSUE TITLE
bug: no pack sounds shows empty list, looks awkward

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#212]
We should not render the pack SoundList if there are no items in the pack:

<img width="1350" alt="Screen Shot 2020-11-19 at 9 02 21 PM" src="https://user-images.githubusercontent.com/6374832/99761281-8dfe6b00-2aaa-11eb-848e-69819e7f925c.png">

**Comment by hamirmahal** [comment]
An example sound that has this issue at the time of this writing is https://freesound-player.vercel.app/sound/396855.

I'll look into this.
