### ISSUE TITLE
ui: redesign implementation: create css variables

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#29]
## Summary
This issue ticket captures the task of create css variables for the secondary color and the primary color. For the current design, the primary color is yellow and the secondary color is black. When dark mode is enabled, we'll switch the values of the css variables so that the primary color becomes the secondary color and vice versa.

## Tasks
- [x] Define primary color (`black`) and secondary  color (`#FBDC57`) css variables
- [x] Swapping the values of the variables on dark mode

## Readings (in recommended order of reading)
* https://www.freecodecamp.org/news/learn-css-variables-in-5-minutes-80cf63b4025d/
* https://www.freecodecamp.org/news/everything-you-need-to-know-about-css-variables-c74d922ea855/
* https://web.dev/prefers-color-scheme/
* https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/
* https://css-tricks.com/dark-modes-with-css/
* https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries
* https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
* https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by akshara-sun** [comment]
Done! Thanks for the links, they were very helpful! I'll make a PR with the updates now!
