### ISSUE TITLE
ui: redesign implementation: use ionicons

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#41]
This ticket outlines how to use ionicons with the project. The UI design uses [ionicons](http://ionicons.com/) for its icons. We'll need to pull in the react library.

### Steps

1. See the [ionicons usage section](https://ionicons.com/usage) for how to import it into our app. You'll need to include the script tag in the `index.html`.
2. Use the icons in the UI. You'll need to look at the figma and try to see which icons were used. Then find the names of those icons.

**Comment by akshara-sun** [comment]
✅ 1. See the ionicons usage section for how to import it into our app. You'll need to include the script tag in the index.html. 

I have a question about the No.2 - What do you mean by "Use the icons in the UI."? Are you suggesting I style the imported icons before closing the issue or would you like me to do the styling in a separate issue? Just want to clarify and make sure. Thanks.

**Comment by amilajack** [comment]
For now, lets just add these two icons to the UI:

<img width="167" alt="Screen Shot 2020-09-22 at 10 30 25 AM" src="https://user-images.githubusercontent.com/6374832/93916590-a1fe3a00-fcbe-11ea-857e-cc8549cf6f70.png">

let me know if that makes sense

**Comment by akshara-sun** [comment]
I have already imported all the icons shown in the Figma. Here's what I'll do, I'll make a PR to showcase the import and then do another PR where they are all styled and formatted according to the Figma.
