### ISSUE TITLE
ui: redesign implementation: implement the header

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#48]
* logo should be SVG
* ignore adding the "featured" link. We don't have that page designed yet

<img width="723" alt="Screen Shot 2020-09-19 at 1 05 38 PM" src="https://user-images.githubusercontent.com/6374832/93688177-d1bc0080-fa78-11ea-8256-a3b7735bcffa.png">

**Comment by akshara-sun** [comment]
So I have to import the logo as an SVG to the approbate file and style the header, correct? 

Also, I am thinking of using Tailwind.css to style this header.

Please let me know if my understanding of this issue is correct.

**Comment by amilajack** [comment]
The header will take some work. I recommend looking into this after https://github.com/amilajack/freesound-player/issues/51

**Comment by akshara-sun** [comment]
For sure! I'll check it out.
