### ISSUE TITLE
ui: redesign implementation: notify user when redirecting to freesound.org for oauth

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#49]
We currently don't notify the user before redirecting them to freesound for oauth, which results in a pretty poor user experience (UX). We should open a prompt alerting the user about the redirection:

<img width="1066" alt="Screen Shot 2020-09-19 at 1 16 32 PM" src="https://user-images.githubusercontent.com/6374832/93688389-578c7b80-fa7a-11ea-9622-987f5bbc19bc.png">

Here's some pseudo code:

```
onLoginClick =() => {
  showModal()
}

onModalConfirmClick =() => {
  redirectToFreesound()
}

<Header>
  <LoginButton onClick={onLoginClick} />
  <Modal onConfirmClick={onModalConfirmClick} />
</Header>
```

## Implementation
* use [react-modal](https://github.com/reactjs/react-modal)

**Comment by hamirmahal** [comment]
[Documentation for `react-modal`](http://reactcommunity.org/react-modal/), in case someone on this page needs it in the future!
