### ISSUE TITLE
feat: add dark mode and toggling support

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#5]
I've heard that viewing blue light before bed is harmful to sleep quality, so I want to work on changing the site's theme to be more conducive toward optimal sleep hygiene.

Current appearance of freesound-player's homepage at the time of this issue's creation:

![freesound-player current background blue 2020-08-07 233857](https://user-images.githubusercontent.com/43425812/89704276-53136580-d907-11ea-8c46-0521ea850357.jpg)

**Comment by amilajack** [comment]
We could use https://github.com/GoogleChromeLabs/dark-mode-toggle for this

**Comment by amilajack** [comment]
Duplicate of #29
