### ISSUE TITLE
ui: redesign implementation: sound title redesign

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#51]
Redesign the current sound title to match the UI design

<img width="709" alt="Screen Shot 2020-09-19 at 1 24 49 PM" src="https://user-images.githubusercontent.com/6374832/93688551-80f9d700-fa7b-11ea-952f-294c0c44c28d.png">

**Comment by hamirmahal** [comment]
For context, here is what that section looks like at the time of this writing:

![Screen Shot 2020-09-19 at 2 04 31 PM](https://user-images.githubusercontent.com/43425812/93689201-0c299b80-fa81-11ea-87e0-2a842d84cc96.png)

The screen shot is from a sound titled [Music Note 6](https://freesound-player.netlify.app/sound/462806).
