### ISSUE TITLE
create and use icon

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#61]
- update the favicon
- updating `manifest.json` to use new icons

**Comment by hamirmahal** [comment]
Potential ideas could be a speaker, or the generic volume icon that's used across operating systems.

**Comment by akshara-sun** [comment]
What about something like this?
![favicon-16x16](https://user-images.githubusercontent.com/49100882/94336654-913d1500-ff99-11ea-92a2-2c4d254bd8e2.png)

**Comment by akshara-sun** [comment]
Is having a T in our Favicon too bland? Here are some examples, I made them using favicon.io.

Circle:
![android-chrome-192x192](https://user-images.githubusercontent.com/49100882/94336707-ec6f0780-ff99-11ea-941e-087d78ce7427.png)

Rounded:
![android-chrome-192x192](https://user-images.githubusercontent.com/49100882/94336709-eed16180-ff99-11ea-9b05-f76ce63c23f4.png)

Square:
![android-chrome-192x192](https://user-images.githubusercontent.com/49100882/94336711-f133bb80-ff99-11ea-86a9-71bee4704ce2.png)

**Comment by akshara-sun** [comment]
There is also this other website that I stumbled upon that has really nice icons:

[https://icons8.com/icons/](url)

Just search up speaker @hamirmahal and there are some pretty cool ones 🙂

**Comment by amilajack** [comment]
Some more icon ideas!

<img width="745" alt="Icon" src="https://user-images.githubusercontent.com/6374832/94348974-70a2a880-fff5-11ea-8a41-f7ab083b32cb.png">

**Comment by hamirmahal** [comment]
I think the following website will be useful for this.

https://realfavicongenerator.net/favicon_checker?protocol=https&site=freesound-player.netlify.app%2F

**Comment by hamirmahal** [comment]
I think #90 closes this. #d647a seems to take care of it.

**Comment by hamirmahal** [comment]
I think #90 closes this. d647a seems to take care of it.

**Comment by hamirmahal** [comment]
I think #90 closes this. d647ad5f782a2d0fc23b42aacabfaddfb8be1d16 seems to take care of it.
