### ISSUE TITLE
gitignore `.DS_Store`

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#65]
Read about gitignore here:
https://git-scm.com/docs/gitignore

Example:
https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/.gitignore#L31

**Comment by akshara-sun** [comment]
I have read through the link and also checked out the example as well. May I close the issue now?

**Comment by amilajack** [comment]
This needs a corresponding PR

**Comment by akshara-sun** [comment]
Gotcha, okay.
