### ISSUE TITLE
add keyboard shortcuts

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#66]
Shortcuts are one of the most useful things for people that frequently access the site. Here's a list of shortcuts I think users will want first:

1. Spacebar plays the current sound
2. Pressing numbers seek the current sound (similar to youtube)
3. `cmd + ?` opens shortcuts panel

## Implementation

1. Implement the shortcuts panel
2. [Use tinykeys](https://github.com/jamiebuilds/tinykeys) to map functionality to shortcuts

For ideas, here are the youtube and soundcloud shortcuts panels:

<img width="1265" alt="Screen Shot 2020-09-24 at 6 54 32 PM" src="https://user-images.githubusercontent.com/6374832/94217650-64083e00-fe97-11ea-8c45-6c27b0d3a9c7.png">

<img width="592" alt="Screen Shot 2020-09-24 at 6 54 46 PM" src="https://user-images.githubusercontent.com/6374832/94217667-6bc7e280-fe97-11ea-9012-d956f3f9e683.png">

**Comment by hamirmahal** [comment]
Closed by #85.

**Comment by hamirmahal** [comment]
Closed by #85.
