### ISSUE TITLE
documentation: link to related repositories in README.md

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#78]
To start, I think we should link to `freesound-client` and `react-wavesurfer.js` in `README.md`. Are there any other related repositories we should add?

**Comment by amilajack** [comment]
+!

**Comment by akshara-sun** [comment]
That's a great idea Hamir! Do you think we should list out what libraries we used as well or is that too much?

**Comment by hamirmahal** [comment]
Linking the two related repositories mentioned in the first post here for easier access.

[`freesound-client`](https://github.com/amilajack/freesound-client)
[`react-wavesurfer.js`](https://github.com/amilajack/react-wavesurfer.js)
