### ISSUE TITLE
hide crop, download and play/pause buttons until sound is done loading

### ISSUE THREAD

**Issue by hamirmahal** [amilajack/freesound-player#89]
I think we should keep the buttons mentioned in the title hidden until a sound has finished loading, so a user isn't able to click a play button for a sound that's nonexistent at the time they clicked it.

Implementation:

I think we can do something straightforward, like adding

`!isLoading && ` ...

to [`Sound.js`](https://github.com/amilajack/freesound-player/blob/master/src/Sound.js), perhaps [at the beginning of line 124](https://github.com/amilajack/freesound-player/blob/9aa8c4a70e4ed5f4ae4657d07898fdaeaf0819e1/src/Sound.js#L124), and enclosing the two icons and button in this conditional render.

**Comment by amilajack** [comment]
Thanks for creating this 😃

**Comment by hamirmahal** [comment]
You're welcome!
