### ISSUE TITLE
bug: link to `/sounds` broken in production

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#9]
See:
* https://github.com/amilajack/freesound-player/blob/master/src/SoundList.js#L9
* https://github.com/amilajack/freesound-player/blob/master/src/App.js#L33

We need to do something similar to this:
https://github.com/amilajack/freesound-player/blob/master/src/App.js#L37

**Comment by hamirmahal** [comment]
Hmm... I don't think I know what the "high-level" consequence of this bug is. I'm navigating <code>freesound-player</code> from <code>https://amilajack.github.io/freesound-player/</code> and I'm able to select a song from the homepage and select songs beneath the **Similar** header just fine.

**Comment by amilajack** [comment]
Interesting that I'm actually not able to reproduce this anymore. Closing
